name = "login-with-cloudflare"
main = "main.ts"
compatibility_date = "2025-06-18"

routes = [
  { pattern = "cloudflare.simplerauth.com", custom_domain = true }
]

[[durable_objects.bindings]]
name = "CODES"
class_name = "CodeDO"

[[migrations]]
new_sqlite_classes = ["CodeDO"]
tag = "v1"

